image: gradle:8.12.1-jdk21

stages:
  - test

test:
  stage: test
  tags:
    - students-buildkit-medium
  script:
    - cd main-service
    - chmod +x ./gradlew
    - ./gradlew test --info
  artifacts:
    reports:
      junit: main-service/build/test-results/test/TEST-*.xml
    paths:
      - main-service/build/test-results/
      - main-service/build/reports/
    when: always
  cache:
    paths:
      - main-service/.gradle/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "dev"'
